### ISSUE TITLE
Invalid ELF header

### ISSUE THREAD

**Issue by felix63** [hydex80/presence_detection_domoticz_fritzbox#4]
When running the script I get some errors:

checking:phone_Lex`
Traceback (most recent call last):
  File "/home/pi/presence_detection_domoticz_fritzbox/fritzhosts.py", line 25, in <module>
    import fritzconnection
  File "/home/pi/presence_detection_domoticz_fritzbox/fritzconnection.py", line 39, in <module>
    from lxml import etree
ImportError: /lib/arm-linux-gnueabihf/libxml2.so.2: invalid ELF header
Sat 13 Mar 20:55:42 UTC 2021 status router and domoticz for phone_Lex are simular, we do nothing

**Comment by hydex80** [comment]
Try pip install -U lxml

This is not a issue of the script but from the dependencie lxml
